### ISSUE TITLE
Unable to embed SPM dynamic library into App

### ISSUE THREAD

**Issue by pavm035** [tuist/tuist#3425]
Unable to embed SPM dynamic library into App 

**To Reproduce**
1. Create sample app
2. Add any open source SPM package which supports dynamic libary
3. Add this as dependency into app

**Expected behavior**
It should embed inside app with sign, if you look in below image ECLogger is says Don't Embed instead it should be like Embed & Sign

**Screenshots**
![Screen Shot 2021-09-09 at 20 30 35](https://user-images.githubusercontent.com/6092412/132683186-6e036b30-72ad-414b-aee4-e9846af7b51d.png)

**Comment by pavm035** [comment]
This is something like defined here https://github.com/yonaskolb/XcodeGen/issues/784

**Comment by saim80** [comment]
I also encountered this very issue. I hope we have a solution soon...

**Comment by protosse** [comment]
so is there any update of this problem currently?

**Comment by danyf90** [comment]
This should be solved if you use Dependencies.swift

**Comment by EricRabil** [comment]
I'm using the latest version of tuist and Dependencies.swift and this issue is not solved for me. I'm unable to find concrete documentation on embedding SPM dependencies, and even forcing all of my productTypes to .staticLibrary does not affect the embedding output - it is always `Do Not Embed`

**Comment by Tyler-Keith-Thompson** [comment]
This is an issue for us, too. We aren't ready to migrate to `Dependencies.swift` just yet. Is there another workaround?
