### ISSUE TITLE
Tuist Cloud is broken again

### ISSUE THREAD

**Issue by mohamadrezakoohkan** [tuist/tuist#5380]
### What problem or need do you have?

We are not able to login into our tuist cloud dashboard, the sign in form throws an incorrect error "Incorrect Email or Password", however we are 100% sure that all of our accounts has correct email address and password entered.

In addition to that, our CI is failing on `tuist cache warm`, we need to clean the caches from the cloud dashboard and its not possible to login and do required actions.

https://cloud.tuist.io/users/sign_in

<img width="636" alt="Screenshot 2023-08-28 at 15 34 01" src="https://github.com/tuist/tuist/assets/37219076/4cf758a3-52cf-4556-a671-7a4d8bcea03d">

### macOS version

13.4.1

### Tuist version

3.12.0

### Xcode version

14.3

**Comment by fortmarek** [comment]
Hey, sorry for the troubles. This should be fixed again cc @pepicrft. Let us know if you still run into issues.

We made some foundational changes lately to prepare for the full launch, we'll work more on the stability now 🙏

**Comment by mohamadrezakoohkan** [comment]
Hey @fortmarek, this issue is not resolved yet, as it stills throws the same error `Invalid Email or password.`.

We have tried with 3 different accounts and only Sing in with GitHub works, our tuist cloud accounts with email and password are not able to log in.

Also it worths to note that, it is not possible to change password or request a new one, since there is no `Forget Password?` button or some recovery options...

**Comment by fortmarek** [comment]
Hey @mohamadrezakoohkan 👋 

We will be adding support for those options, you are right these are not available right now. I can help you better in our [Slack](https://join.slack.com/t/tuistapp/shared_invite/zt-1y667mjbk-s2LTRX1YByb9EIITjdLcLw) as I'd need some of your personal information to resolve the issue.

**Comment by fortmarek** [comment]
We've added a possibility for `Forget password` and `Resend confirmation email`:
![image](https://github.com/tuist/tuist/assets/9371695/70964fb2-30fa-49b8-8644-2f8777520f9b)
![image](https://github.com/tuist/tuist/assets/9371695/b0564d73-6a81-4130-bfed-f7476e1ec9fe)
![image](https://github.com/tuist/tuist/assets/9371695/d6b8a89b-fcb5-45d7-9d42-d3cb9a8c29fa)

This will deploy in ~1 hour. Closing this issue, let us know if you need any further assistance from our side
