### ISSUE TITLE
“tuist” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by makleso6** [tuist/tuist#6549]
### What happened?

can not run tuist

### How do we reproduce it?

install tuist via homebrew

### Error log

“tuist” cannot be opened because the developer cannot be verified. macOS cannot verify that this app is free from malware.

### macOS version

14.4

### Tuist version

4.21.1/4.21.2

### Xcode version

15.4

**Comment by maximilianlemberg-awl** [comment]
I had the same issue. The workaround is to confirm that you want to open the script by manually allowing it to run. 
See this post from apple on how to do it: [Apple Support - Safely open apps on your Mac
](https://support.apple.com/en-us/102445)

**Comment by pepicrft** [comment]
You are getting this error because the binaries are not signed and notarized. We have in the backlog fixing that, but we haven't got to that yet unfortunately. You can trust those binaries through the macOS and proceed with using it.

**Comment by frankois944** [comment]
Hello,

Same error for  ProjectDescription.framework

**Comment by fortmarek** [comment]
Hey 👋 

This should have been fixed in the latest release. We can reopen if that is not the case.

**Comment by iHamzaaK** [comment]
Hey, I installed the latest release 4.39.1 and i am still getting this error.

![Image](https://github.com/user-attachments/assets/06646fd3-11d8-4a62-b334-73dd2e66ec3f)

**Comment by jmkitavi** [comment]
Hello, currently blocked on this for version 4.55.6

<img width="372" height="374" alt="Image" src="https://github.com/user-attachments/assets/9e81a812-eea3-40a0-9748-2dcd4c627e60" />
