### ISSUE TITLE
AppExtension from another Project is not embedded into the App

### ISSUE THREAD

**Issue by rock88** [tuist/tuist#6734]
### What happened?

Hi! 
I encountered a bug - if I define an AppExtension target in another `Project.swift` file and try to include it in the main App's dependencies, it will not be embed into the App:

<img width="480" alt="Screenshot 2024-09-16 at 18 02 38" src="https://github.com/user-attachments/assets/bd1a167c-42be-4882-964f-895e75ff3844">

I use
```swift
.project(target: "LiveActivity", path: .relativeToRoot("LiveActivity"))
```
In the `LiveActivityApp/Project.swift` and I expect that the `LiveActivity` target will be embedded in the App like this:

<img width="480" alt="Screenshot 2024-09-16 at 18 03 41" src="https://github.com/user-attachments/assets/436941ae-61ee-47cf-92d3-b78acb11e564">

### How do we reproduce it?

Example project - https://github.com/rock88/tuist-app-extension-issue
```
tuist install
tuist generate
```

### Error log

No error

### macOS version

14.6.1

### Tuist version

4.26.0

### Xcode version

15.4

**Comment by minhaaan** [comment]
I think you should put the widget target in the same project as the app target

```swift
let project = Project(
    name: "LiveActivityApp",
    options: .options(automaticSchemesOptions: .disabled),
    targets: [
        .target(
            name: "LiveActivityApp",
            destinations: [.iPhone],
            product: .app,
            bundleId: "com.test.LiveActivityApp",
            deploymentTargets: .iOS("15.0"),
            infoPlist: .extendingDefault(with: [
                "UILaunchStoryboardName": "LaunchScreen",
                "NSCameraUsageDescription": "Example",
                "NSContactsUsageDescription": "Example",
                "NSLocationAlwaysAndWhenInUseUsageDescription": "Example",
                "NSLocationWhenInUseUsageDescription": "Example",
                "NSPhotoLibraryUsageDescription": "Example",
                "NSSupportsLiveActivities": .boolean(true)
            ]),
            sources: ["Sources/**"],
            resources: ["Resources/**"],
            dependencies: [
                .external(name: "LiveActivityKit"),
                .external(name: "Localization"),
                .target(name: "LiveActivity"),
            ]
        ),
        .target(
            name: "LiveActivity",
            destinations: [.iPhone],
            product: .appExtension,
            bundleId: "com.test.LiveActivityApp.live-activity",
            deploymentTargets: .iOS("16.2"),
            infoPlist: .extendingDefault(with: [
                "NSExtension": [
                    "NSExtensionPointIdentifier": "com.apple.widgetkit-extension",
                ]
            ]),
            sources: ["Sources/**"], // need change this
            dependencies: [
                .external(name: "LiveActivityKit"),
                .external(name: "Localization"),
            ]
        ),
    ],
    resourceSynthesizers: []
)
```

**Comment by rock88** [comment]
Hi @minhaaan,
Yes, you are right, if define App and LiveActivity in the same `Project.swift` [file](https://github.com/rock88/tuist-app-extension-issue/blob/aecbd71d62fc5563ede9c9c5eaae38a2e3868906/Project.swift), everything works fine.
But in App with LiveActivity/NotificationService app extensions single `Project.swift` looks big, so I thought that it would be possible to separate the main application and extensions into different `Project.swift` files:
```
App/
  Sources/
  Tests/
  Project.swift

LiveActivity/
  Sources/
  Project.swift

NotificationServiceExtension/
  Sources/
  Project.swift

Workspace.swift
```

**Comment by minhaaan** [comment]
Oh. That's actually weird 😕

**Comment by TamarMilchtaich** [comment]
This issue should be solved by: https://github.com/tuist/tuist/pull/6820

**Comment by fortmarek** [comment]
Closing, we can reopen if needed 🤞

**Comment by flexaargo** [comment]
I think this issue is still occurring? Might not be the exact same issue, but Previews will refuse to work in the app extension target if it is defined in a separate Project file from the App. The app extension does seem to say it is embedded in the xcodeproj but the Preview error seems to indicate otherwise. Building to device and sim does properly embed widget tho.

Here is the Preview error I see:
```
== DATE:

    Monday, December 30, 2024 at 2:35:22 AM Pacific Standard Time
    
    2024-12-30T10:35:22Z



== PREVIEW UPDATE ERROR:

    AppExtensionNeedsContainingAppError<UpdateGraphItem<XcodeGraphSource>>: AbacusHomeScreenWidget.appex must be in an app
    
    The app extension ”AbacusHomeScreenWidget.appex” needs to be embedded in an app in order to use previews



== BUILD GRAPH:

    AbacusHomeScreenWidget.appex (#3)



== PREVIEW UPDATE ERROR:

    AppExtensionNeedsContainingAppError<UpdateGraphItem<XcodeGraphSource>>: AbacusHomeScreenWidget.appex must be in an app
    
    The app extension ”AbacusHomeScreenWidget.appex” needs to be embedded in an app in order to use previews



== BUILD GRAPH:

    AbacusHomeScreenWidget.appex (#3)



== VERSION INFO:

    Tools: 16C5032a
    OS:    24C101
    PID:   95271
    Model: MacBook Pro
    Arch:  arm64e



== ENVIRONMENT:

    openFiles = [
        /Users/alexfargo/Developer/Apps/Currency/mobile/CurrencyApp/Extensions/Widgets/AbacusHomeScreenWidget/Sources/CommonDenominationsWidget.swift
    ]
    wantsNewBuildSystem = true
    newBuildSystemAvailable = true
    activeScheme = Abacus
    activeRunDestination = iPhone 16 Pro variant iphonesimulator arm64
    workspaceArena = [x]
    buildArena = [x]
    buildableEntries = [
        AbacusHomeScreenWidget.appex
    ]
    runMode = JIT Executor



== SELECTED RUN DESTINATION:

    Simulator - iOS 18.2 | iphonesimulator | arm64 | iPhone 16 Pro | no proxy



== EXECUTION MODE OVERRIDES:

    Workspace JIT mode user setting: true
    Falling back to Dynamic Replacement: false



== PACKAGE RESOLUTION ERRORS:

    



== REFERENCED SOURCE PACKAGES:

    



== JIT LINKAGE:

    Run Destination: 33BB55B8-55BA-4128-B7E9-E6F10B0236DD-iphonesimulator18.2-arm64-iphonesimulator
    JIT Link Description {
        3:AbacusHomeScreenWidget.appex
    }
    



== SESSION GROUP 9289:

    workspace identifier: WorkspaceIdentifier(identifier: 7D2C3F0A-EFA9-4558-BF6C-E2C0F47640D2)
    providers: [
        Preview Provider | Registry-CommonDenominationsWidget.swift#1[preview] [Editor(9241)]
    ]
    translation units: [
        /Users/alexfargo/Developer/Apps/Currency/mobile/CurrencyApp/Extensions/Widgets/AbacusHomeScreenWidget/Sources/CommonDenominationsWidget.swift
    ]
    attributes: [
        Editor(9241):     []
    ]
    session: 9294
    request sessions: [
        Registry[Registry-CommonDenominationsWidget.swift#1[preview] (line 235)]: not completed
    ]



== UPDATE SESSION 9294:

    Start Date: Monday, December 30, 2024 at 2:34:54 AM Pacific Standard Time
    Timing {
        Elapsed Time: 1.472722053527832s
        a96dfff81033e454,757247694.517476,1.472722053527832s,,PreviewUpdateSession,id:9294
        c082a0b27e21718a,757247694.586411,0.0003039836883544922s,,MakeBuildGraph,
        7f41b2bc69630ed1,757247694.588266,1.338428020477295s,,WorkspaceBuild,
        4fc561cb724ca5c3,757247695.926916,0.04532599449157715s,,AllBuiltTargetDescriptions,
        4f7edfc795747d51,757247695.92698,0.007743954658508301s,,IDEBuiltTargetDescriptionRequest,
        d5363fd613878bde,757247695.934778,0.03728199005126953s,,ProcessBuiltTargetDescription,AbacusHomeScreenWidget
        60f5e753c3318b,757247695.990166,0.45154809951782227s,,ThunkBuild,CommonDenominationsWidget.swift
    }
    Preview Preflight {
        UpdaterStore {
            updaterLimit: single
            expectedAbandonedIdentifiers: [6581, 2541, 5350, 6627, 5130, 5393, 8298, 7730, 5228, 7684, 8252, 4457, 4689, 8117, 7258, 5078, 7212, 8163]
        }
        Simulator {
            platform: iphonesimulator
            device: F52F8A59-B299-4E0E-98CD-473184EE4057 iPhone 16 Pro
            buildNumber: 22C150
            runtimePath: /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime
        }
    }
    Preview Provider {
        UpdaterStore {
            updaterLimit: single
            expectedAbandonedIdentifiers: [6581, 2541, 5350, 6627, 5130, 5393, 8298, 7730, 5228, 7684, 8252, 4457, 4689, 8117, 7258, 5078, 7212, 8163]
        }
        Simulator {
            platform: iphonesimulator
            device: F52F8A59-B299-4E0E-98CD-473184EE4057 iPhone 16 Pro
            buildNumber: 22C150
            runtimePath: /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime
        }
    }
    Build Graph {
        AbacusHomeScreenWidget.appex (#3)
           sourceFile(file:///Users/alexfargo/Developer/Apps/Currency/mobile/CurrencyApp/Extensions/Widgets/AbacusHomeScreenWidget/Sources/CommonDenominationsWidget.swift -> CommonDenominationsWidget.swift) (#1)
           CommonDenominationsWidget.swift (#2)
    }
    Update Plan {
        iOS [arm64 iphonesimulator18.2 iphonesimulator] (iPhone 16 Pro, 33BB55B8-55BA-4128-B7E9-E6F10B0236DD-iphonesimulator18.2-arm64-iphonesimulator), [], thinning disabled, thunking enabled) {
            Destination: iPhone 16 Pro 33BB55B8-55BA-4128-B7E9-E6F10B0236DD | default device for iphonesimulator [
                AbacusHomeScreenWidget appExtension - Previews {
                    execution point packs [
                        [source: CommonDenominationsWidget.swift, role: Previews] (in AbacusHomeScreenWidget)
                    ]
                    translation units [
                        CommonDenominationsWidget.swift (in AbacusHomeScreenWidget.appex)
                    ]
                    modules [
                        AbacusHomeScreenWidget.appex
                    ]
                    jit link description [
                        AbacusHomeScreenWidget.appex
                    ]
                }
            ]
        }
    }



== POWER STATE LOGS:

    12/30/2024, 2:33 AM Received power source state: Battery Powered (lowPowerMode: false, status: charged, level: 100%)
    12/30/2024, 2:33 AM No device power state user override user default value.Current power state: Full Power
```
