### ISSUE TITLE
The git command exited with error code 2

### ISSUE THREAD

**Issue by moalekseev** [tuist/tuist#6736]
### What happened?

When I enter any command with tuist this message appear(for example tuist version):

The 'git' command exited with error code 2 and message:
error: Нет такого внешнего репозитория «origin»(No external repository)

Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

### How do we reproduce it?

1. enter any command with tuist in terminal

### Error log

```sh 
The 'git' command exited with error code 2 and message:
error: Нет такого внешнего репозитория «origin»

Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose```

### macOS version

14.7

### Tuist version

4.26.0

### Xcode version

16.0

**Comment by moalekseev** [comment]
resolved

**Comment by tangzhen** [comment]
@moalekseev  Could you please reopen this issue?

This issue was introduced after version 4.26.0, and I have checked the latest 4.27.0; the issue still persists.

When running the tuist command in a folder tracked by Git, the issue occurs. However, if the folder is not set up with Git, all commands run successfully.

**Comment by moalekseev** [comment]
ok if it help to you i added repository `origin` and error disappear

> @moalekseev Could you please reopen this issue?
> 
> This issue was introduced after version 4.26.0, and I have checked the latest 4.27.0; the issue still persists.
> 
> When running the tuist command in a folder tracked by Git, the issue occurs. However, if the folder is not set up with Git, all commands run successfully.

**Comment by stefano-mondino-deltatre** [comment]
Same issue happening here on a new project where we are still waiting to be provided with a valid repo URL

**Comment by fortmarek** [comment]
Hey, folks!

I created a PR to fix the issue: https://github.com/tuist/tuist/pull/6784

As a workaround, you can create arbitrary commit and you should no longer run into the issues.

**Comment by finebel** [comment]
> As a workaround, you can create an arbitrary commit in your new project and you should no longer run into the issues.

For me, the issue still persists. I have three commits in my repository and no remote set.

Tested with Tuist 4.29.1 and Xcode 15.4

![Screenshot 2024-10-13 at 12 53 03](https://github.com/user-attachments/assets/c7f17ae8-46c7-4dbb-bd97-3cfff941582c)

**Comment by fortmarek** [comment]
Hey @finebel 👋 

Can you provide steps to reproduce?

**Comment by finebel** [comment]
@fortmarek Yes, here are the steps to reproduce:  
```

mkdir TuistSample
cd TuistSample
git init
mise use tuist@latest
tuist init --platform ios
git add . 
git commit -m "Initial commit"
tuist version // <- outputs error shown above
```

**Comment by fortmarek** [comment]
I see, you're right! Reopening.
