### ISSUE TITLE
Support configuring the access level of synthesized interfaces

### ISSUE THREAD

**Issue by chrisjrex** [tuist/tuist#7541]
### Why is this needed?

When using `-enable-upcoming-feature InternalImportsByDefault`, there is a compilation issue in the generated resource access code.

The enablement of the Swift feature `AccessLevelOnImport` causes compiling issues with synthesized interfaces defaulting to public.

This is because returned `InternalImportsByDefault` flag requires that if your API returns values from an imported framework on a public API interface, then you must make that import `Public`.

![Build Error](https://github.com/user-attachments/assets/0d6ae93c-843b-42d7-a6ff-0df252f9891f)

- [swift-evolution proposal](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0409-access-level-on-imports.md)
- [tuist slack discussion](https://tuist-community.slack.com/archives/C018QG7U7SN/p1746011685887669)

### Steps to address the need

1. We should provide an interface where developers can configure the access level of those synthesized interfaces.

2. (optional/nice to have) I think a good addition would also be to check the graph and if nothing depends on a project. then its accessors should default to internal

**Comment by pepicrft** [comment]
Detecting the enablement of the flag at generation-time will be a bit tricky, since the flag can be defined in `.xcconfig` files, which can import other `.xcconfig` files and define values that are dynamically resolved at build-time.
Therefore, I'm inclined to expose an interface to declare the access level that should be used.

In the same way we have [`Project.options`](https://github.com/tuist/XcodeGraph/blob/main/Sources/XcodeGraph/Models/ProjectOptions.swift), we can have [`Target.options`] with an API along the lines of:

```swift
let target = Target(
  name: "MyApp", 
  options: .options(bundleAccessor: .bundleAccessor(accessLevel: .public)
)
```

That information can then be used at generation time to override [this default](https://github.com/tuist/tuist/blob/3b8ed97626ca0f9e472bd9ba9edec28446ec559f/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift#L284C25-L284C51). What do you think @tuist/community-core ?

**Comment by JoeSzymanskiNoom** [comment]
You might be able to simplify this by using the `hasFeature` check (https://www.swift.org/blog/using-upcoming-feature-flags/)

I think something like this might work for everyone:

```
#if hasFeature(InternalImportsByDefault)
public import Foundation
#else
import Foundation
#endif
```

**Comment by chrisjrex** [comment]
@pepicrft I implemented @JoeSzymanskiNoom's idea: https://github.com/tuist/tuist/pull/7550

**Comment by philipbel** [comment]
I think this issue should be reopened. This is still a problem for generated asset accessors (`TuistAssets+*.swift`).

The imports look like this:

```Swift
//...
#if os(macOS)
  import AppKit
#elseif os(iOS)
  import UIKit
#elseif os(tvOS) || os(watchOS)
  import UIKit
#endif
#if canImport(SwiftUI)
  import SwiftUI
#endif
// ...
```

Edit: I am using Tuist 4.52.0
